//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 07:52:35 PM IST 
//


package com.cgi.integration.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cgi.integration.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Wc_QNAME = new QName("", "wc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cgi.integration.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WcType }
     * 
     */
    public WcType createWcType() {
        return new WcType();
    }

    /**
     * Create an instance of {@link ContentTsType }
     * 
     */
    public ContentTsType createContentTsType() {
        return new ContentTsType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WcType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wc")
    public JAXBElement<WcType> createWc(WcType value) {
        return new JAXBElement<WcType>(_Wc_QNAME, WcType.class, null, value);
    }

}
