//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 12:47:28 PM IST 
//


package com.encomm.models.content.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.encomm.models.content.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListofResponseObject_QNAME = new QName("", "listofResponseObject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.encomm.models.content.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListofResponseObjectType }
     * 
     */
    public ListofResponseObjectType createListofResponseObjectType() {
        return new ListofResponseObjectType();
    }

    /**
     * Create an instance of {@link ResponsesType }
     * 
     */
    public ResponsesType createResponsesType() {
        return new ResponsesType();
    }

    /**
     * Create an instance of {@link ParaTypeType }
     * 
     */
    public ParaTypeType createParaTypeType() {
        return new ParaTypeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListofResponseObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "listofResponseObject")
    public JAXBElement<ListofResponseObjectType> createListofResponseObject(ListofResponseObjectType value) {
        return new JAXBElement<ListofResponseObjectType>(_ListofResponseObject_QNAME, ListofResponseObjectType.class, null, value);
    }

}
