//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 01:47:30 AM IST 
//


package com.cgi.integration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MergeDetails" type="{urn://com.cgi.services/schema}MergeDetailsType" minOccurs="0"/&gt;
 *         &lt;element name="splitDetails" type="{urn://com.cgi.services/schema}splitDetailsType" minOccurs="0"/&gt;
 *         &lt;element name="lineOfBusiness"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Lending"/&gt;
 *               &lt;enumeration value="Deposits"/&gt;
 *               &lt;enumeration value="CreditCards"/&gt;
 *               &lt;enumeration value="Services"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="appDetails" type="{urn://com.cgi.services/schema}appDetailsType"/&gt;
 *         &lt;element name="coappDetails" type="{urn://com.cgi.services/schema}coappDetailsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "mergeDetails",
    "splitDetails",
    "lineOfBusiness",
    "appDetails",
    "coappDetails"
})
public class BodyType {

    @XmlElement(name = "MergeDetails")
    protected MergeDetailsType mergeDetails;
    protected SplitDetailsType splitDetails;
    @XmlElement(required = true)
    protected String lineOfBusiness;
    @XmlElement(required = true)
    protected AppDetailsType appDetails;
    protected CoappDetailsType coappDetails;

    /**
     * Gets the value of the mergeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MergeDetailsType }
     *     
     */
    public MergeDetailsType getMergeDetails() {
        return mergeDetails;
    }

    /**
     * Sets the value of the mergeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MergeDetailsType }
     *     
     */
    public void setMergeDetails(MergeDetailsType value) {
        this.mergeDetails = value;
    }

    /**
     * Gets the value of the splitDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SplitDetailsType }
     *     
     */
    public SplitDetailsType getSplitDetails() {
        return splitDetails;
    }

    /**
     * Sets the value of the splitDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitDetailsType }
     *     
     */
    public void setSplitDetails(SplitDetailsType value) {
        this.splitDetails = value;
    }

    /**
     * Gets the value of the lineOfBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineOfBusiness() {
        return lineOfBusiness;
    }

    /**
     * Sets the value of the lineOfBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineOfBusiness(String value) {
        this.lineOfBusiness = value;
    }

    /**
     * Gets the value of the appDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AppDetailsType }
     *     
     */
    public AppDetailsType getAppDetails() {
        return appDetails;
    }

    /**
     * Sets the value of the appDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppDetailsType }
     *     
     */
    public void setAppDetails(AppDetailsType value) {
        this.appDetails = value;
    }

    /**
     * Gets the value of the coappDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CoappDetailsType }
     *     
     */
    public CoappDetailsType getCoappDetails() {
        return coappDetails;
    }

    /**
     * Sets the value of the coappDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoappDetailsType }
     *     
     */
    public void setCoappDetails(CoappDetailsType value) {
        this.coappDetails = value;
    }

}
