//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 01:47:30 AM IST 
//


package com.cgi.integration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="formSeq" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formDetailsType", propOrder = {
    "formId",
    "formTitle",
    "formSeq"
})
public class FormDetailsType {

    @XmlElement(required = true)
    protected String formId;
    @XmlElement(required = true)
    protected String formTitle;
    @XmlElement(required = true)
    protected String formSeq;

    /**
     * Gets the value of the formId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormId() {
        return formId;
    }

    /**
     * Sets the value of the formId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormId(String value) {
        this.formId = value;
    }

    /**
     * Gets the value of the formTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormTitle() {
        return formTitle;
    }

    /**
     * Sets the value of the formTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormTitle(String value) {
        this.formTitle = value;
    }

    /**
     * Gets the value of the formSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormSeq() {
        return formSeq;
    }

    /**
     * Sets the value of the formSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormSeq(String value) {
        this.formSeq = value;
    }

}
