//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 01:47:30 AM IST 
//


package com.cgi.integration.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cgi.integration.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Source_QNAME = new QName("urn://com.cgi.services/schema", "source");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cgi.integration.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link IntegrationRequest }
     * 
     */
    public IntegrationRequest createIntegrationRequest() {
        return new IntegrationRequest();
    }

    /**
     * Create an instance of {@link IntegrationResponse }
     * 
     */
    public IntegrationResponse createIntegrationResponse() {
        return new IntegrationResponse();
    }

    /**
     * Create an instance of {@link DocFetchRequest }
     * 
     */
    public DocFetchRequest createDocFetchRequest() {
        return new DocFetchRequest();
    }

    /**
     * Create an instance of {@link DocFetchResponse }
     * 
     */
    public DocFetchResponse createDocFetchResponse() {
        return new DocFetchResponse();
    }

    /**
     * Create an instance of {@link FormDetailsType }
     * 
     */
    public FormDetailsType createFormDetailsType() {
        return new FormDetailsType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link MergeDetailsType }
     * 
     */
    public MergeDetailsType createMergeDetailsType() {
        return new MergeDetailsType();
    }

    /**
     * Create an instance of {@link SplitDetailsType }
     * 
     */
    public SplitDetailsType createSplitDetailsType() {
        return new SplitDetailsType();
    }

    /**
     * Create an instance of {@link AppDetailsType }
     * 
     */
    public AppDetailsType createAppDetailsType() {
        return new AppDetailsType();
    }

    /**
     * Create an instance of {@link CoappDetailsType }
     * 
     */
    public CoappDetailsType createCoappDetailsType() {
        return new CoappDetailsType();
    }

    /**
     * Create an instance of {@link BodyType }
     * 
     */
    public BodyType createBodyType() {
        return new BodyType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn://com.cgi.services/schema", name = "source")
    public JAXBElement<SourceType> createSource(SourceType value) {
        return new JAXBElement<SourceType>(_Source_QNAME, SourceType.class, null, value);
    }

}
