//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 01:47:30 AM IST 
//


package com.cgi.integration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for splitDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="splitDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="docId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="startPageNo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="endPageNo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "splitDetailsType", propOrder = {
    "docId",
    "startPageNo",
    "endPageNo"
})
public class SplitDetailsType {

    @XmlElement(required = true)
    protected String docId;
    protected int startPageNo;
    protected int endPageNo;

    /**
     * Gets the value of the docId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocId() {
        return docId;
    }

    /**
     * Sets the value of the docId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocId(String value) {
        this.docId = value;
    }

    /**
     * Gets the value of the startPageNo property.
     * 
     */
    public int getStartPageNo() {
        return startPageNo;
    }

    /**
     * Sets the value of the startPageNo property.
     * 
     */
    public void setStartPageNo(int value) {
        this.startPageNo = value;
    }

    /**
     * Gets the value of the endPageNo property.
     * 
     */
    public int getEndPageNo() {
        return endPageNo;
    }

    /**
     * Sets the value of the endPageNo property.
     * 
     */
    public void setEndPageNo(int value) {
        this.endPageNo = value;
    }

}
