//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.05 at 07:23:20 PM IST 
//


package com.compare.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paraseq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paraType", propOrder = {
	"Id",	
    "paraseq",
    "content"
})
public class ParaType {
	
	
    protected int id;
	
	protected FileInfoType fileInfoType;
    protected int paraseq;
    @XmlElement(required = true)
    protected String content;
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return the fileInfoType
	 */
	public FileInfoType getFileInfoType() {
		return fileInfoType;
	}
	/**
	 * @param fileInfoType the fileInfoType to set
	 */
	public void setFileInfoType(FileInfoType fileInfoType) {
		this.fileInfoType = fileInfoType;
	}
	/**
	 * @return the paraseq
	 */
	public int getParaseq() {
		return paraseq;
	}
	/**
	 * @param paraseq the paraseq to set
	 */
	public void setParaseq(int paraseq) {
		this.paraseq = paraseq;
	}
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
       

}
