//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.04 at 03:07:00 PM IST 
//


package com.operationtool.highchart.models.hrbu;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pyramidAccountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pyramidAccountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BuLead" type="{}BuLeadType"/>
 *         &lt;element name="GroupLead" type="{}GroupLeadType"/>
 *         &lt;element name="Director" type="{}DirectorType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)

public class PyramidAccountType {

    protected String name;
    protected BuLeadType buLead;
    protected GroupLeadType groupLead;
    protected List<DirectorType> director;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the buLead property.
     * 
     * @return
     *     possible object is
     *     {@link BuLeadType }
     *     
     */
    public BuLeadType getBuLead() {
        return buLead;
    }

    /**
     * Sets the value of the buLead property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuLeadType }
     *     
     */
    public void setBuLead(BuLeadType value) {
        this.buLead = value;
    }

    /**
     * Gets the value of the groupLead property.
     * 
     * @return
     *     possible object is
     *     {@link GroupLeadType }
     *     
     */
    public GroupLeadType getGroupLead() {
        return groupLead;
    }

    /**
     * Sets the value of the groupLead property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupLeadType }
     *     
     */
    public void setGroupLead(GroupLeadType value) {
        this.groupLead = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the director property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DirectorType }
     * 
     * 
     */
    public List<DirectorType> getDirector() {
        if (director == null) {
            director = new ArrayList<DirectorType>();
        }
        return this.director;
    }

}
