//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.29 at 02:55:21 PM IST 
//


package com.cgi.integration.models.content;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="formId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="formTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versionNo" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="paraSeq" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentType", propOrder = {
    "contentId",
    "formId",
    "formTitle",
    "versionNo",
    "paraSeq",
    "content"
})
public class ContentType {

    protected int contentId;
    @XmlElement(required = true)
    protected String formId;
    @XmlElement(required = true)
    protected String formTitle;
    protected float versionNo;
    protected short paraSeq;
    @XmlElement(required = true)
    protected String content;

    /**
     * Gets the value of the contentId property.
     * 
     */
    public int getContentId() {
        return contentId;
    }

    /**
     * Sets the value of the contentId property.
     * 
     */
    public void setContentId(int value) {
        this.contentId = value;
    }

    /**
     * Gets the value of the formId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormId() {
        return formId;
    }

    /**
     * Sets the value of the formId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormId(String value) {
        this.formId = value;
    }

    /**
     * Gets the value of the formTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormTitle() {
        return formTitle;
    }

    /**
     * Sets the value of the formTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormTitle(String value) {
        this.formTitle = value;
    }

    /**
     * Gets the value of the versionNo property.
     * 
     */
    public float getVersionNo() {
        return versionNo;
    }

    /**
     * Sets the value of the versionNo property.
     * 
     */
    public void setVersionNo(float value) {
        this.versionNo = value;
    }

    /**
     * Gets the value of the paraSeq property.
     * 
     */
    public short getParaSeq() {
        return paraSeq;
    }

    /**
     * Sets the value of the paraSeq property.
     * 
     */
    public void setParaSeq(short value) {
        this.paraSeq = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

}
