//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.29 at 02:55:21 PM IST 
//


package com.cgi.integration.models.content;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cgi.integration.models.content package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentTab_QNAME = new QName("", "ContentTab");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cgi.integration.models.content
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ContentTabType }
     * 
     */
    public ContentTabType createContentTabType() {
        return new ContentTabType();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentTabType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ContentTab")
    public JAXBElement<ContentTabType> createContentTab(ContentTabType value) {
        return new JAXBElement<ContentTabType>(_ContentTab_QNAME, ContentTabType.class, null, value);
    }

}
