//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.30 at 09:36:19 PM IST 
//

package com.operationtool.database.models.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "candidate")
@Entity(name = "candidate")
@Table(name = "candidate")
@XmlAccessorType(XmlAccessType.FIELD)
public class Candidate {

	@Column(name = "resourceID", nullable = true, insertable = true, updatable = true, unique = true)
	@Id
	@NotNull
	protected String resourceID;

	@Column(name = "resourcename")
	protected String resourcename;
	@Column(name = "resourceemailid")
	protected String resourceemailid;
	@Column(name = "doj")
	protected String doj;
	@Column(name = "designation")
	protected String designation;
	@Column(name = "gender")
	protected String gender;
	@Column(name = "shortdesignation")
	protected String shortdesignation;
	@Column(name = "cgiexp")
	protected String cgiexp;
	@Column(name = "prevexp")
	protected String prevexp;
	@Column(name = "totalexp")
	protected String totalexp;
	@Column(name = "membertype")
	protected String membertype;
	@Column(name = "location")
	protected String location;
	@Column(name = "sublocation")
	protected String sublocation;
	@Column(name = "skillsfamily")
	protected String skillsfamily;
	@Column(name = "competency")
	protected String competency;
	@Column(name = "subcompetency")
	protected String subcompetency;
	@Column(name = "skillcategory")
	protected String skillcategory;
	@Column(name = "departmentid")
	protected String departmentid;
	@Column(name = "departmentdescription")
	protected String departmentdescription;
	@Column(name = "assignmentstartdate")
	protected String assignmentstartdate;
	@Column(name = "assignmentenddate")
	protected String assignmentenddate;
	@Column(name = "employeestatus")
	protected String employeestatus;
	@Column(name = "releasemonth")
	protected String releasemonth;
	@Column(name = "reportingmanager")
	protected String reportingmanager;
	@Column(name = "reportingmanageremailid")
	protected String reportingmanageremailid;
	@Column(name = "projectmanagerdept11inthehrtree")
	protected String projectmanagerdept11inthehrtree;
	@Column(name = "directordept10inthehrtree")
	protected String directordept10inthehrtree;
	@Column(name = "groupleaddept9inthehrtree")
	protected String groupleaddept9inthehrtree;
	@Column(name = "buleaddept8inthehrtree")
	protected String buleaddept8inthehrtree;
	@Column(name = "pyramidaccounthrbu")
	protected String pyramidaccounthrbu;
	@Column(name = "hrbu")
	protected String hrbu;
	public String getHrbu() {
		return hrbu;
	}

	public void setHrbu(String hrbu) {
		this.hrbu = hrbu;
	}

	public String getResourceID() {
		return resourceID;
	}

	public void setResourceID(String resourceID) {
		this.resourceID = resourceID;
	}

	public String getResourcename() {
		return resourcename;
	}

	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	public String getResourceemailid() {
		return resourceemailid;
	}

	public void setResourceemailid(String resourceemailid) {
		this.resourceemailid = resourceemailid;
	}

	public String getDoj() {
		return doj;
	}

	public void setDoj(String doj) {
		this.doj = doj;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getShortdesignation() {
		return shortdesignation;
	}

	public void setShortdesignation(String shortdesignation) {
		this.shortdesignation = shortdesignation;
	}

	public String getCgiexp() {
		return cgiexp;
	}

	public void setCgiexp(String cgiexp) {
		this.cgiexp = cgiexp;
	}

	public String getPrevexp() {
		return prevexp;
	}

	public void setPrevexp(String prevexp) {
		this.prevexp = prevexp;
	}

	public String getTotalexp() {
		return totalexp;
	}

	public void setTotalexp(String totalexp) {
		this.totalexp = totalexp;
	}

	public String getMembertype() {
		return membertype;
	}

	public void setMembertype(String membertype) {
		this.membertype = membertype;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSublocation() {
		return sublocation;
	}

	public void setSublocation(String sublocation) {
		this.sublocation = sublocation;
	}

	public String getSkillsfamily() {
		return skillsfamily;
	}

	public void setSkillsfamily(String skillsfamily) {
		this.skillsfamily = skillsfamily;
	}

	public String getCompetency() {
		return competency;
	}

	public void setCompetency(String competency) {
		this.competency = competency;
	}

	public String getSubcompetency() {
		return subcompetency;
	}

	public void setSubcompetency(String subcompetency) {
		this.subcompetency = subcompetency;
	}

	public String getSkillcategory() {
		return skillcategory;
	}

	public void setSkillcategory(String skillcategory) {
		this.skillcategory = skillcategory;
	}

	public String getDepartmentid() {
		return departmentid;
	}

	public void setDepartmentid(String departmentid) {
		this.departmentid = departmentid;
	}

	public String getDepartmentdescription() {
		return departmentdescription;
	}

	public void setDepartmentdescription(String departmentdescription) {
		this.departmentdescription = departmentdescription;
	}

	public String getAssignmentstartdate() {
		return assignmentstartdate;
	}

	public void setAssignmentstartdate(String assignmentstartdate) {
		this.assignmentstartdate = assignmentstartdate;
	}

	public String getAssignmentenddate() {
		return assignmentenddate;
	}

	public void setAssignmentenddate(String assignmentenddate) {
		this.assignmentenddate = assignmentenddate;
	}

	public String getEmployeestatus() {
		return employeestatus;
	}

	public void setEmployeestatus(String employeestatus) {
		this.employeestatus = employeestatus;
	}

	public String getReleasemonth() {
		return releasemonth;
	}

	public void setReleasemonth(String releasemonth) {
		this.releasemonth = releasemonth;
	}

	public String getReportingmanager() {
		return reportingmanager;
	}

	public void setReportingmanager(String reportingmanager) {
		this.reportingmanager = reportingmanager;
	}

	public String getReportingmanageremailid() {
		return reportingmanageremailid;
	}

	public void setReportingmanageremailid(String reportingmanageremailid) {
		this.reportingmanageremailid = reportingmanageremailid;
	}

	public String getProjectmanagerdept11inthehrtree() {
		return projectmanagerdept11inthehrtree;
	}

	public void setProjectmanagerdept11inthehrtree(String projectmanagerdept11inthehrtree) {
		this.projectmanagerdept11inthehrtree = projectmanagerdept11inthehrtree;
	}

	public String getDirectordept10inthehrtree() {
		return directordept10inthehrtree;
	}

	public void setDirectordept10inthehrtree(String directordept10inthehrtree) {
		this.directordept10inthehrtree = directordept10inthehrtree;
	}

	public String getGroupleaddept9inthehrtree() {
		return groupleaddept9inthehrtree;
	}

	public void setGroupleaddept9inthehrtree(String groupleaddept9inthehrtree) {
		this.groupleaddept9inthehrtree = groupleaddept9inthehrtree;
	}

	public String getBuleaddept8inthehrtree() {
		return buleaddept8inthehrtree;
	}

	public void setBuleaddept8inthehrtree(String buleaddept8inthehrtree) {
		this.buleaddept8inthehrtree = buleaddept8inthehrtree;
	}

	public String getPyramidaccounthrbu() {
		return pyramidaccounthrbu;
	}

	public void setPyramidaccounthrbu(String pyramidaccounthrbu) {
		this.pyramidaccounthrbu = pyramidaccounthrbu;
	}

}
